name: core_ui
description: Shared Green Design System, Themes, Colors and Widgets
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
